"""Generate deployable Python graph modules from JSON agent definitions.

The langosh CLI authors/edits the canonical `definition.json` (LLM-friendly,
structured). This module turns that definition into a Python module under
`langosh-agents/graphs/<id>/__init__.py` that exports a compiled `graph`.

Both langosh-server (loads at boot via `langgraph.json`) and the langosh CLI
(`/test`, `/graph`) treat the generated module as the source of truth for what
runs.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from .registry import graph_dir

DEFAULT_MODEL = "anthropic:claude-sonnet-4-5-20250929"

# Map tool-name → (module_path, symbol). Extend as we add tool packages.
_TOOL_IMPORTS: dict[str, tuple[str, str]] = {
    # files
    "read_file": ("langosh_tools.files", "read_file"),
    "write_file": ("langosh_tools.files", "write_file"),
    "edit_file": ("langosh_tools.files", "edit_file"),
    "list_directory": ("langosh_tools.files", "list_directory"),
    "glob_files": ("langosh_tools.files", "glob_files"),
    "grep_files": ("langosh_tools.files", "grep_files"),
    # python sandbox
    "execute_python": ("langosh_tools.python_exec", "execute_python"),
    # web
    "web_search": ("langosh_tools.websearch", "web_search"),
    "fetch_rss": ("langosh_tools.rss", "fetch_rss"),
    # slack (optional dep: slack-sdk)
    "send_slack_message": ("langosh_tools.slack", "send_slack_message"),
    "ask_slack": ("langosh_tools.slack", "ask_slack"),
    # telegram (optional dep: python-telegram-bot)
    "send_telegram_message": ("langosh_tools.telegram", "send_telegram_message"),
    "ask_telegram": ("langosh_tools.telegram", "ask_telegram"),
}


def _resolve_tool_imports(tool_names: list[str]) -> tuple[list[str], list[str]]:
    """Return (import_lines, tool_symbols).

    Unknown tools raise ValueError so the user sees a clear error instead of a
    runtime ImportError when the server tries to load the generated module.
    """
    by_module: dict[str, list[str]] = {}
    for name in tool_names:
        if name not in _TOOL_IMPORTS:
            raise ValueError(
                f"Unknown tool '{name}'. Add an entry to _TOOL_IMPORTS in "
                f"agents/codegen.py or remove it from the definition."
            )
        mod, symbol = _TOOL_IMPORTS[name]
        by_module.setdefault(mod, []).append(symbol)
    import_lines = [
        f"from {mod} import {', '.join(sorted(set(syms)))}"
        for mod, syms in sorted(by_module.items())
    ]
    tool_symbols = [_TOOL_IMPORTS[n][1] for n in tool_names]
    return import_lines, tool_symbols


def _compile_simple_source(definition: dict, graph_id: str) -> str:
    """Generate Python source for a simple ReAct-style agent."""
    system_prompt = definition.get("system_prompt", "You are a helpful assistant.")
    tool_names: list[str] = definition.get("tools", [])
    model = definition.get("model") or DEFAULT_MODEL

    tool_imports, tool_symbols = _resolve_tool_imports(tool_names)

    safe_prompt = system_prompt.replace('"""', "'''")
    tools_arg = "[" + ", ".join(tool_symbols) + "]"
    imports_block = "\n".join(tool_imports)

    return (
        f'"""{graph_id} — generated from definition.json.\n'
        f"\n"
        f"DO NOT EDIT THIS FILE BY HAND.\n"
        f"Edit definition.json (or use `langosh` /agents /edit) and the CLI\n"
        f"will regenerate this module on save.\n"
        f'"""\n'
        f"\n"
        f"from langgraph.prebuilt import create_react_agent\n"
        f"{imports_block}\n"
        f"\n"
        f"DEFAULT_MODEL = {model!r}\n"
        f'SYSTEM_PROMPT = """{safe_prompt}"""\n'
        f"\n"
        f"graph = create_react_agent(\n"
        f"    model=DEFAULT_MODEL,\n"
        f"    tools={tools_arg},\n"
        f"    prompt=SYSTEM_PROMPT,\n"
        f")\n"
    )


def compile_to_source(definition: dict, functions: list[dict], graph_id: str) -> str:
    """Generate Python source for a graph from its JSON definition.

    `functions` holds {"name": ..., "code": ...} entries for "function" nodes
    in custom agents. Currently only "simple" agents are supported.
    """
    agent_type = definition.get("type", "simple")
    if agent_type == "simple":
        return _compile_simple_source(definition, graph_id)
    if agent_type == "custom":
        raise NotImplementedError(
            "Custom agents (state schema + nodes + edges) aren't supported "
            "by codegen yet. For now, write the graph module by hand under "
            "<agents_path>/graphs/<id>/__init__.py and add a langgraph.json entry."
        )
    raise ValueError(f"Unknown agent type: {agent_type}")


def _hash_inputs(definition: dict, functions: list[dict]) -> str:
    payload = {
        "definition": definition,
        "functions": sorted(functions, key=lambda f: f["name"]),
    }
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()


def write_compiled_graph(graph_id: str, definition: dict, functions: list[dict]) -> Path:
    """Write the generated Python module to <agents_path>/graphs/<id>/__init__.py.

    Also stores `definition.json`, `functions/*.py`, and a `.compile_hash` file
    so we can detect drift between source and generated output.

    Returns the path to the generated `__init__.py`.
    """
    folder = graph_dir(graph_id)
    folder.mkdir(parents=True, exist_ok=True)
    (folder / "definition.json").write_text(
        json.dumps(definition, indent=2, ensure_ascii=False) + "\n"
    )

    # Custom function files (used by "function" node type — not yet exposed
    # through codegen, but persisted for round-tripping).
    if functions:
        funcs_dir = folder / "functions"
        funcs_dir.mkdir(exist_ok=True)
        for fn in functions:
            (funcs_dir / f"{fn['name']}.py").write_text(fn["code"])

    source = compile_to_source(definition, functions, graph_id)
    init_path = folder / "__init__.py"
    init_path.write_text(source)
    (folder / ".compile_hash").write_text(_hash_inputs(definition, functions))
    return init_path
